<a href="https://colab.research.google.com/github/2vie/machine-learning/blob/main/%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_%EA%B0%9C%EC%9A%94.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [3]:
X, y = np.arange(10).reshape((5,2)), range(5)
print(X)
print(list(y))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0, 1, 2, 3, 4]


In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

print(X_train)
print(y_train)
print(X_test)
print(y_test)

[[2 3]
 [8 9]
 [0 1]
 [6 7]]
[1, 4, 0, 3]
[[4 5]]
[2]


**텐서**

In [5]:
t=np.array([0,1,2,3,4])
print(t)
print(t.ndim)
print(t.shape)

[0 1 2 3 4]
1
(5,)


In [6]:
t=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print(t)
print(t.ndim)
print(t.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
2
(4, 3)


**파이토치**

In [7]:
import torch
t=torch.FloatTensor([0,1,2,3,4])
print(t)
print(t.dim())
print(t.shape)
print(t.size())

tensor([0., 1., 2., 3., 4.])
1
torch.Size([5])
torch.Size([5])


In [8]:
t=torch.FloatTensor(([0,1,2],[3,4,5],[6,7,8],[9,10,11]))
print(t)
print(t.dim())
print(t.size())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
2
torch.Size([4, 3])


**텐서-브로드캐스팅**

In [9]:
#같은 행렬크기끼리의 계산
a=torch.FloatTensor(([1,2]))
b=torch.FloatTensor(([3,3]))
a+b

tensor([4., 5.])

In [10]:
#브로드캐스팅: 차원 다른 경우 차원 자동변환해서 계산
a=torch.FloatTensor(([1,2]))
b=torch.FloatTensor([3])
a+b

tensor([4., 5.])

In [11]:
#1*2 텐서랑 2*1 텐서 계산
a=torch.FloatTensor([[1,2]]) #1*2
b=torch.FloatTensor([[3],[4]]) #2*1
a+b

tensor([[4., 5.],
        [5., 6.]])

In [12]:
#3d 텐서
t=torch.FloatTensor([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]])
print(t.size())

torch.Size([2, 2, 3])


In [13]:
#(x,3) 크기로 변경 - 열은 3으로 하고 행은 알아서 계산
t2=t.view([-1,3])
print(t2)
print(t2.size())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [14]:
#(x,1,3) 크기로 변경 -
t3 = t2.view([-1,1,3]) #3차원인데 전체 열은 1*3 행렬이 들어간 것처럼, 전체 행은 알아서(-1) 맞추기
print(t3)
print(t3.size())

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


**squeeze, unsqueeze**-1인 차원제거, 추가

In [15]:
t4=t3.squeeze() #크기가 1인 차원 자동제거. 아까 t3 사이즈가 [4,1,3]이었으니까 이 1을 제거함
print(t4)
print(t4.size()) #그럼 다시 사이즈 [4,3]인 2차원 텐서가 됨

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [17]:
t5=t4.unsqueeze(0) #새로운 차원 하나 추가. unsqueeze(0): 0인 자리 즉 가장 앞에 1인 차원 추가해줌
print(t5)
print(t5.size()) #그럼 새로운 [1,4,3] 3차원 텐서가 됨. 이건 하나의 샘플에 행4열3인 2차원이 있는 형태

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.],
         [ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
torch.Size([1, 4, 3])


**자료형변경**

In [18]:
t6=t5.long() #실수형이었던 텐서를 정수형으로 바꿔주기(int64)
print(t6)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])
